FROM apache/gravitino-iceberg-rest:1.3.0

RUN curl -L -o /opt/gravitino-iceberg-rest-server/libs/postgresql-42.7.7.jar https://repo1.maven.org/maven2/org/postgresql/postgresql/42.7.7/postgresql-42.7.7.jar

