replicaCount: 1

imagePullSecrets:
  - name: ghcr-pull-secret
image:
  repository: ghcr.io/openprojectx/tg-crawler
  tag: 0.1.0-SNAPSHOT-61137e21
  pullPolicy: IfNotPresent

persistence:
  enabled: true
  accessModes: [ "ReadWriteMany" ]
  storageClassName: "ceph-filesystem"
  size: 32Gi
  mountPath: "/app/tg-session"
  volumeName: tg-crawler-session

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  className: nginx
  hosts:
    - host: tg-crawler.openprojectx.cn-guangzhou-a.k8s.openprojectx.org
      paths:
        - path: /
          pathType: Prefix
  tls:
    enabled: true
    secretName: tg-crawler-tls  # this secret must exist in the same namespace

http-route:
  enabled: true
  namespace: openprojectx
  service:  tg-crawler
  hostname: tg-crawler.openprojectx.cn-guangzhou-a.k8s.openprojectx.org
  port: 8080

resources:
  requests:
    cpu: 4
    memory: 1Gi
  limits:
    cpu: 8
    memory: 8Gi


config:
  applicationYaml: |
    server:
      port: 8080
    spring:
      application:
        name: tg-crawler
